#!/bin/tcsh
#PBS -N Cherenkov
#PBS -l nodes=1:hima:gpu:ppn=20
#PBS -l walltime=10:00:00
#PBS -j oe

cd $PBS_O_WORKDIR

module load anaconda3/2021.11
module load cuda/11.7
conda activate ptorch
python /sciclone/home/jgiroux/Cherenkov/train_mnf.py --config /sciclone/home/jgiroux/Cherenkov/config/default_config.json


